@URL = http://localhost:3000/api

# getAll
###
GET {{URL}}/posts

# getAll ( Paginated )
###
GET {{URL}}/posts?page=2&perPage=2

# getById
###
GET {{URL}}/posts/31

# getAllPostsByAuthor
###
GET {{URL}}/posts/author/2

# getAllPostsByAuthor ( Paginated )
###
GET {{URL}}/posts/author/2?page=1&perPage=1

# create
###
POST {{URL}}/posts
Content-Type: application/json

  {
    "titulo": "Como acabar los controles del API",
    "descripcion": "Estrategias para no abandonar tu entrenamiento.",
    "categoria_id": 3,
    "autor_id": 4
  }

# updateById
###
PUT {{URL}}/posts/31
Content-Type: application/json

  {
    "titulo": "Como acabar los controles del API de una vez",
    "descripcion": "Estrategias para no abandonar tu entrenamiento.",
    "categoria_id": 2,
    "autor_id": 4
  }

# deleteById
###
DELETE {{URL}}/posts/31