@URL = http://localhost:3000/api

# getAll
###
GET {{URL}}/authors

# getAll ( Paginated )
###
GET {{URL}}/authors?page=1&perPage=2

# getById
###
GET {{URL}}/authors/34

# create
###
POST {{URL}}/authors
Content-Type: application/json

{
    "nombre": "Lluis",
    "email": "lalsina883@gmail.com",
    "imagen": "https://randomuser.me/api/portraits/men/2.jpg"
}

# updateById
###
PUT {{URL}}/authors/34
Content-Type: application/json

{
    "nombre": "Lluis5   ",
    "email": "lalsina883@gmail.com",
    "imagen": "https://randomuser.me/api/portraits/men/2.jpg"
}

# deleteById
###
DELETE {{URL}}/authors/34