@URL = http://localhost:3000/api

GET {{URL}}/authors

###
GET {{URL}}/authors?page=1&perPage=1

###
GET {{URL}}/authors/4

{
  "data": [
    {
      "id": 9,
      "nombre": "Lluis",
      "email": "lalsina883@gmail.com",
      "imagen": "https://randomuser.me/api/portraits/men/2.jpg"
    }
  ]
}

###
POST {{URL}}/authors
Content-Type: application/json

{
    "nombre": "Lluis",
    "email": "lalsina883@gmail.com",
    "imagen": "https://randomuser.me/api/portraits/men/2.jpg"
}

###
PUT {{URL}}/authors/11
Content-Type: application/json

{
    "nombre": "Lluis2",
    "email": "lalsina883@gmail.com2",
    "imagen": "https://randomuser.me/api/portraits/men/2.jpg"
}

###
DELETE {{URL}}/authors/11